#:schema node_modules/wrangler/config-schema.json
name = "consumer"
main = "consumer.js"
compatibility_date = "2024-07-12"
compatibility_flags = ["nodejs_compat"]

services = [{ binding = "RPC_WORKER", service = "rpc-worker" }]
